version: '3.8'

services:
  web:
    build: .
    command: sh -c "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/test_1
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
 
volumes:
  postgres_data: